name: zebra_handheld_scanner
description: "A Flutter plugin for seamlessly communicating with and controlling Zebra Bluetooth BLE/SPP handheld barcode scanners natively on iOS and Android."
version: 0.0.4
homepage: https://github.com/armin1440/zebra_scanner

environment:
  sdk: ^3.10.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.zebra_scanner
        pluginClass: ZebraScannerPlugin
      ios:
        pluginClass: ZebraScannerPlugin
